[versions]
android = "7.2.2"
coil = "2.1.0"
dagger = "2.42"
emoji = "1.1.0"
kotlin = "1.7.10"
lifecycle = "2.4.1"
retrofit = "2.9.0"
room = "2.4.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-androidExtensions = { id = "org.jetbrains.kotlin.android.extensions", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version = "6.6.1" }

[libraries]
androidx-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core = "androidx.core:core-ktx:1.8.0"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-emoji2-core = { module = "androidx.emoji2:emoji2", version.ref = "emoji" }
androidx-emoji2-views = { module = "androidx.emoji2:emoji2-views", version.ref = "emoji" }
androidx-fragment = "androidx.fragment:fragment-ktx:1.4.1"
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-paging = "androidx.paging:paging-runtime-ktx:2.1.2"
androidx-palette = "androidx.palette:palette:1.0.0"
androidx-preference = "androidx.preference:preference-ktx:1.2.0"
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-core = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-swiperefreshlayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
androidx-webkit = "androidx.webkit:webkit:1.4.0"
coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
dagger-android-core = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger" }
desugar = "com.android.tools:desugar_jdk_libs:1.1.5"
flexbox = "com.google.android.flexbox:flexbox:3.0.0"
fragnav = "com.ncapdevi:frag-nav:3.3.0"
javax-jaxb-api = "javax.xml.bind:jaxb-api:2.3.0"
junit = "junit:junit:4.13.2"
kotlinpoet = "com.squareup:kotlinpoet:1.12.0"
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.2"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.3.2"
logback = "ch.qos.logback:logback-classic:1.2.9"
material = "com.google.android.material:material:1.7.0-alpha02"
mockito-core = "org.mockito:mockito-core:3.11.1"
mockito-kotlin = "com.nhaarman:mockito-kotlin:1.3.0"
okhttp-logging = "com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.7"
okio = "com.squareup.okio:okio:3.2.0"
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
rxjava-core = "io.reactivex.rxjava2:rxjava:2.1.6"
rxjava-rxkotlin = "io.reactivex.rxjava2:rxkotlin:2.1.0"
slf4j = "org.slf4j:slf4j-api:1.7.32"
