[versions]
accompanist = "0.32.0"
android = "8.1.2"
coil = "2.5.0"
compose = "2023.03.00"
composeMultiplatform = "1.5.3"
emoji = "1.4.0"
kotlin = "1.9.10"
ktor = "2.3.5"
lifecycle = "2.6.2"
moko = "0.23.0"
paging = "3.3.0-alpha02-0.4.0"
sqldelight = "2.0.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
compose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "1.9.10-1.0.13" }
licenseReport = { id = "com.github.jk1.dependency-license-report", version = "2.5" }
moko-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko" }
skie = { id = "co.touchlab.skie", version = "0.5.2" }
spotless = { id = "com.diffplug.spotless", version = "6.22.0" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

[libraries]
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
androidx-activity-compose = "androidx.activity:activity-compose:1.8.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-browser = "androidx.browser:browser:1.6.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core = "androidx.core:core-ktx:1.12.0"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-emoji2-core = { module = "androidx.emoji2:emoji2", version.ref = "emoji" }
androidx-fragment = "androidx.fragment:fragment-ktx:1.6.1"
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-paging-common = { module = "app.cash.paging:paging-common", version.ref = "paging" }
androidx-paging-compose-common = { module = "app.cash.paging:paging-compose-common", version.ref = "paging" }
androidx-paging-runtime-android = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-paging-runtime-ios = { module = "app.cash.paging:paging-runtime-uikit", version.ref = "paging" }
androidx-palette = "androidx.palette:palette:1.0.0"
androidx-splashscreen = "androidx.core:core-splashscreen:1.0.1"
bignum = "com.ionspin.kotlin:bignum:0.3.8"
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
compose-bom = { module = "dev.chrisbanes.compose:compose-bom", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material-core2 = { module = "androidx.compose.material:material" }
compose-material-core3 = { module = "androidx.compose.material3:material3" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-material-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-ui-core = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
desugar = "com.android.tools:desugar_jdk_libs:2.0.3"
fluid-currency = "io.fluidsonic.currency:fluid-currency:0.13.0"
junit = "junit:junit:4.13.2"
koin-android = { module = "io.insert-koin:koin-android", version = "3.5.0" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version = "3.5.0" }
koin-core = { module = "io.insert-koin:koin-core", version = "3.5.0" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.6"
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.1"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0"
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-contentNegociation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
material-core = "com.google.android.material:material:1.10.0"
moko-resources-core = { module = "dev.icerock.moko:resources", version.ref = "moko" }
moko-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko" }
okio = "com.squareup.okio:okio:3.6.0"
sqldelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
unicode-codepoints = "de.cketti.unicode:kotlin-codepoints:0.6.1"
uri-kmp = "com.eygraber:uri-kmp:0.0.15"
