[versions]
android = "7.4.0"
chucker = "3.5.2"
coil = "2.2.2"
compose = "2023.01.00"
emoji = "1.2.0"
kotlin = "1.8.0"
ktor = "2.2.2"
lifecycle = "2.5.1"
okhttp = "5.0.0-alpha.11"
room = "2.5.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "1.8.0-1.0.9" }
licenseReport = { id = "com.github.jk1.dependency-license-report", version = "2.1" }
spotless = { id = "com.diffplug.spotless", version = "6.13.0" }

[libraries]
accompanist-systemuicontroller = "com.google.accompanist:accompanist-systemuicontroller:0.28.0"
accompanist-webview = "com.google.accompanist:accompanist-webview:0.28.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.6.1"
androidx-annotation = "androidx.annotation:annotation:1.5.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.5.1"
androidx-browser = "androidx.browser:browser:1.4.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-emoji2-core = { module = "androidx.emoji2:emoji2", version.ref = "emoji" }
androidx-fragment = "androidx.fragment:fragment-ktx:1.5.5"
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-paging-runtime = "androidx.paging:paging-runtime-ktx:3.1.1"
androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha17"
androidx-palette = "androidx.palette:palette:1.0.0"
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-core = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-splashscreen = "androidx.core:core-splashscreen:1.0.0"
chucker-noop = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
chucker-runtime = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material-core2 = { module = "androidx.compose.material:material" }
compose-material-core3 = { module = "androidx.compose.material3:material3" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-material-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class" }
compose-runtime-core = { module = "androidx.compose.runtime:runtime" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-ui-core = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
desugar = "com.android.tools:desugar_jdk_libs:2.0.0"
irc = "fr.outadoc:Kale:v1.2.1"
junit = "junit:junit:4.13.2"
koin-android = { module = "io.insert-koin:koin-android", version = "3.3.2" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version = "3.4.1" }
koin-core = { module = "io.insert-koin:koin-core", version = "3.3.2" }
kotlinpoet = "com.squareup:kotlinpoet:1.12.0"
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.0"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-contentNegociation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-io = { module = "io.ktor:ktor-io", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
leakcanary = "com.squareup.leakcanary:leakcanary-android:2.10"
material-core = "com.google.android.material:material:1.8.0"
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okio = "com.squareup.okio:okio:3.3.0"
