[versions]
android = "7.3.1"
chucker = "3.5.2"
coil = "2.1.0"
compose = "1.3.1"
emoji = "1.1.0"
koin = "3.2.0"
kotlin = "1.7.21"
lifecycle = "2.4.1"
retrofit = "2.9.0"
room = "2.4.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "1.7.21-1.0.8" }
spotless = { id = "com.diffplug.spotless", version = "6.6.1" }

[libraries]
accompanist-systemuicontroller = "com.google.accompanist:accompanist-systemuicontroller:0.25.1"
accompanist-webview = "com.google.accompanist:accompanist-webview:0.27.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.5.1"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-emoji2-core = { module = "androidx.emoji2:emoji2", version.ref = "emoji" }
androidx-fragment = "androidx.fragment:fragment-ktx:1.4.1"
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-paging-runtime = "androidx.paging:paging-runtime-ktx:3.1.1"
androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha17"
androidx-palette = "androidx.palette:palette:1.0.0"
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-core = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-splashscreen = "androidx.core:core-splashscreen:1.0.0"
androidx-webkit = "androidx.webkit:webkit:1.4.0"
chucker-noop = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
chucker-runtime = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material-core2 = "androidx.compose.material:material:1.3.1"
compose-material-core3 = "androidx.compose.material3:material3:1.0.1"
compose-material-icons = "androidx.compose.material:material-icons-extended:1.3.1"
compose-material-windowSizeClass = "androidx.compose.material3:material3-window-size-class:1.1.0-alpha02"
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-ui-core = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
desugar = "com.android.tools:desugar_jdk_libs:1.1.5"
irc = "fr.outadoc:Kale:v1.2.1"
junit = "junit:junit:4.13.2"
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlinpoet = "com.squareup:kotlinpoet:1.12.0"
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.2"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.3.2"
leakcanary = "com.squareup.leakcanary:leakcanary-android:2.9.1"
material-core = "com.google.android.material:material:1.7.0"
mockito-core = "org.mockito:mockito-core:4.8.1"
mockito-kotlin = "com.nhaarman:mockito-kotlin:1.3.0"
okhttp-logging = "com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.10"
okio = "com.squareup.okio:okio:3.2.0"
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
