package com.github.andreyasadchy.xtra.util

object C {
    const val GAME = "game"
    const val TOKEN = "token"
    const val USER = "user"
    const val USERNAME = "username"
    const val USER_ID = "user_id"
    const val CHANNEL = "channel"
    const val DOWNLOAD_STORAGE = "downloadStorage"
    const val ASPECT_RATIO_LANDSCAPE = "aspectRatioLandscape"
    const val TWITCH_EMOTES_URL = "https://static-cdn.jtvnw.net/emoticons/v2/"
    const val FIRST_LAUNCH1 = "first_launch"
    const val LANDSCAPE_CHAT_WIDTH = "landscape_chat_width"
    const val KEY_CHAT_OPENED = "key_chat_opened"
    const val AD_BLOCKER = "adblock"
    const val THEME = "theme"
    const val PORTRAIT_COLUMN_COUNT = "columnsPortrait"
    const val LANDSCAPE_COLUMN_COUNT = "columnsLandscape"
    const val COMPACT_STREAMS = "compactStreams"
    const val UI_ROUNDUSERIMAGE = "ui_rounduserimage"
    const val UI_VIEWCOUNT = "ui_viewcount"
    const val UI_STARTONFOLLOWED = "ui_startonfollowed"
    const val UI_STATUSBAR = "ui_statusbar"
    const val UI_NAVBAR = "ui_navbar"
    const val UI_LANGUAGE = "ui_language"
    const val UI_CUTOUTMODE = "ui_cutoutmode"
    const val PICTURE_IN_PICTURE = "pictureInPicture"
    const val PLAYER_DOUBLETAP = "player_doubletap"
    const val PLAYER_ASPECT = "player_aspect"
    const val PLAYER_CHATTOGGLE = "player_chattoggle"
    const val PLAYER_SLEEP = "player_sleep"
    const val PLAYER_FULLSCREEN = "player_fullscreen"
    const val PLAYER_VIEWERICON = "player_viewericon"
    const val PLAYER_DOWNLOAD = "player_download"
    const val PLAYER_MINIMIZE = "player_minimize"
    const val PLAYER_CHANNEL = "player_channel"
    const val PLAYER_QUALITY = "player_quality"
    const val PLAYER_SAVEQUALITY = "player_savequality"
    const val CHAT_RANDOMCOLOR = "chat_randomcolor"
    const val CHAT_BOLDNAMES = "chat_boldnames"
    const val CHAT_EMOTEQUALITY = "chat_emotequality"
    const val CHAT_BADGEQUALITY = "chat_badgequality"
    const val CHAT_LIMIT = "chat_limit"
    const val CHAT_GIFS = "chat_gifs"
    const val CHAT_GIFS2 = "chat_gifs2"
}