package com.github.andreyasadchy.xtra.util

object C {
    const val CHANNEL_ID = "channel_id"
    const val CHANNEL_LOGIN = "channel_login"
    const val CHANNEL_DISPLAYNAME = "channel_displayname"
    const val CHANNEL_PROFILEIMAGE = "channel_profileimage"
    const val CHANNEL_UPDATELOCAL = "channel_updatelocal"
    const val TOKEN = "token"
    const val USERNAME = "username"
    const val USER_ID = "user_id"
    const val FIRST_LAUNCH = "first_launch"
    const val FIRST_LAUNCH1 = "first_launch1"
    const val FIRST_LAUNCH2 = "first_launch2"
    const val ANIMATED_EMOTES = "animatedGifEmotes"
    const val CHAT_LIMIT = "chat_limit"
    const val CHAT_TIMESTAMPS = "chat_timestamps"
    const val CHAT_RECENT = "chat_recent"
    const val CHAT_RECENT_LIMIT = "chat_recent_limit"
    const val CHAT_SHOW_USERNOTICE = "chat_show_usernotice"
    const val CHAT_SHOW_CLEARMSG = "chat_show_clearmsg"
    const val CHAT_SHOW_CLEARCHAT = "chat_show_clearchat"
    const val CHAT_PUBSUB_ENABLED = "chat_pubsub_enabled"
    const val HELIX_CLIENT_ID = "helix_client_id"
    const val HELIX_REDIRECT = "helix_redirect"
    const val DEBUG_CHAT_FULLMSG = "debug_chat_fullmsg"
}
