title: Just Chatting
description: A free and open source app focused on a great Twitch chat experience, for Android, iOS and desktop.
url: https://just-chatting.app
repository: outadoc/just-chatting

include: [".well-known"]
exclude: ["Gemfile", "Gemfile.lock", "vendor", "README.md"]

plugins:
  - jekyll-seo-tag

sass:
  style: compressed

links:
  github: https://github.com/outadoc/just-chatting
  releases: https://github.com/outadoc/just-chatting/releases/latest
