name: Release new version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release

    concurrency:
      group: deploy-to-store
      cancel-in-progress: true

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

      - name: Compute unique version code
        id: version
        run: echo "::set-output name=version::$(git rev-list HEAD --count)"

      - name: Build app bundle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            bundleRelease
            "-PreleaseKeystorePassword=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}"
            "-PexternalVersionName=${{ steps.date.outputs.date }}.${{ steps.version.outputs.version }}"
            "-PexternalVersionCode=${{ steps.version.outputs.version }}"
            "-PenableLogging=false"

      - name: Upload app bundle to GitHub
        uses: actions/upload-artifact@v3.1.3
        with:
          name: apk
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Publish nightly build to internal track
        uses: r0adkll/upload-google-play@9cf8fd30c9e616ec761db3b9abb2b0f15842ce58
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_INTERNAL_APP_SHARING }}
          packageName: fr.outadoc.justchatting
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          status: completed

      - name: Create GitHub release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: "v${{ steps.date.outputs.date }}.${{ steps.version.outputs.version }}"
          commit: main
          makeLatest: true
          generateReleaseNotes: true
          artifacts: app/build/outputs/bundle/release/app-release.aab
