name: Release new version

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get tag version name
        id: tag
        uses: frabert/replace-string-action@cfa94ab0520558c86227623a272f9a5d244181c9
        with:
          pattern: "^v(.+)$"
          string: ${{ github.ref_name }}
          replace-with: "$1"

      - name: Compute unique version code
        id: version
        run: echo "::set-output name=version::$(git rev-list HEAD --count)"

      - name: Build app bundle
        run: ./gradlew bundleRelease "-PreleaseKeystorePassword=${RELEASE_KEYSTORE_PASSWORD}" "-PexternalVersionName=${VERSION_NAME}" "-PexternalVersionCode=${VERSION_CODE}"
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          VERSION_NAME: ${{ steps.tag.outputs.replaced }}
          VERSION_CODE: ${{ steps.version.outputs.version }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: apk
          path: app/build/outputs/bundle/release/app-release.aab

      - uses: r0adkll/upload-google-play@78c9e796b1035c94169c101d8e46cb880194bfc3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_INTERNAL_APP_SHARING }}
          packageName: fr.outadoc.justchatting
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          status: draft
