name: Release new version

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Get tag version name
        id: tag
        uses: frabert/replace-string-action@c71139d1c5bef2be70342d76dba2d17aa4b19da4
        with:
          pattern: "^v(.+)$"
          string: ${{ github.ref_name }}
          replace-with: "$1"

      - name: Compute unique version code
        id: version
        run: echo "::set-output name=version::$(git rev-list HEAD --count)"

      - name: Build app bundle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            bundleRelease 
            "-PreleaseKeystorePassword=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}"
            "-PexternalVersionName=${{ steps.tag.outputs.replaced }}"
            "-PexternalVersionCode=${{ steps.version.outputs.version }}"

      - name: Upload app bundle to GitHub
        uses: actions/upload-artifact@v3.1.1
        with:
          name: apk
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Publish release build to internal track
        uses: r0adkll/upload-google-play@78c9e796b1035c94169c101d8e46cb880194bfc3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_INTERNAL_APP_SHARING }}
          packageName: fr.outadoc.justchatting
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          status: completed
