name: Check DB migrations

on:
  pull_request:
    paths:
      - 'shared/src/commonMain/sqldelight/**'

jobs:
  verify:
    name: Check SQLDelight migrations
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check SQLDelight migrations
        run: ./gradlew shared:verifySqlDelightMigration
