name: Release - Create tag

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  create-release:
    name: Create release and tag
    runs-on: ubuntu-latest
    environment: release

    concurrency:
      group: create-release
      cancel-in-progress: true

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Check if last commit is tagged
        id: check-tagged-commit
        continue-on-error: true
        run: |
          if [[ $(git tag --points-at HEAD) ]]; then
            echo "Last commit is tagged"
            exit 0
          else
            echo "Last commit is not tagged"
            exit 1
          fi

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m')"

      - name: Compute unique version code
        id: version
        run: echo "::set-output name=version::$(git rev-list HEAD --count)"

      - name: Create GitHub release
        uses: ncipollo/release-action@v1.18.0
        if: steps.check-tagged-commit.outputs.result == '1'
        with:
          tag: "v${{ steps.date.outputs.date }}.${{ steps.version.outputs.version }}"
          commit: main
          makeLatest: true
          generateReleaseNotes: true
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
