name: Release - Create tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-to-store
      cancel-in-progress: true

    permissions:
      contents: write

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m')"

      - name: Compute unique version code
        id: version
        run: echo "::set-output name=version::$(git rev-list HEAD --count)"

      - name: Create GitHub release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: "v${{ steps.date.outputs.date }}.${{ steps.version.outputs.version }}"
          commit: main
          makeLatest: true
          generateReleaseNotes: true
