name: Release - Deploy Desktop

on:
  release:
    types:
      - released

jobs:
  deploy:
    name: ${{ matrix.target }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    environment: deploy

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            os: macos-latest
            target: macos
            lipo-arch: arm64
          - arch: amd64
            os: windows-2019
            target: windows
          - arch: amd64
            os: ubuntu-latest
            target: linux

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m')"

      - name: Compute unique version code
        id: version
        run: echo "::set-output name=version::$(git rev-list HEAD --count)"

      - name: Build packages
        run: |
          ./gradlew app-desktop:package \
          "-PexternalVersionCode=${{ steps.version.outputs.version }}" \
          "-PexternalVersionName=${{ steps.date.outputs.date }}.${{ steps.version.outputs.version }}" \
          "-PenableLogging=false"

      - name: Upload packages to GitHub
        uses: actions/upload-artifact@v4.6.2
        with:
          path: app-desktop/build/compose/binaries/main
          name: build-${{ matrix.target }}-${{ matrix.arch }}

      - name: Update release
        uses: johnwbyrd/update-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: app-desktop/build/compose/binaries/main/*
          release: ${{ github.event.release.name }}
