name: Build iOS app

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-15

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_16.2.app/Contents/Developer'

      - name: List SDKs
        run: xcodebuild -showsdks

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Mise
        uses: jdx/mise-action@v2
        with:
          install: false

      - name: Install Mise dependencies
        run: mise install
        working-directory: app-ios

      - name: Build iOS app
        run: tuist build --platform ios
        working-directory: app-ios
