name: Build iOS app

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-15

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_16.4.app/Contents/Developer'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Set up Mise
        uses: jdx/mise-action@v3
        with:
          install: false

      - name: Install Mise dependencies
        run: mise install
        working-directory: app-ios

      - name: Build iOS app
        run: tuist build
        working-directory: app-ios
